### PR TITLE
Added love.conf

### PR DESCRIPTION
**Pull request by davisdude**
Sorry if this isn't formatted to your specifications, I tried to take information straight from the wiki like the other ones, but it wasn't really as clear.

### CODE REVIEW

**Comment by davisdude** [comment]
Also, it might be useful to list options available in love.conf

**Comment by rm-code** [comment]
Hi @davisdude,

thanks for the PR! I was thinking about how we could add the config files. The options could probably work as a subtable: See https://love2d.org/wiki/Mesh:setVertices and https://github.com/rm-code/love-api/blob/master/modules/graphics/types/Mesh.lua#L606.

I also wonder if the config file should be moved outside of the callbacks table - maybe simply to its own "config" table inside of the love_api.lua?

Best wishes
Robert

**Comment by davisdude** [comment]
Alright, how's this?

**Comment by rm-code** [comment]
Looks good to me! I still think it should be moved to a separate table so it doesn't cause conflicts with scripts for auto-generating callback snippets if you know what I mean. Something like 

```
config = {
... insert here
},
callbacks = {
...
}
```
What do you think?

We could also add the [default values](https://github.com/rm-code/love-api/blob/61f4ee081a2279d3d9cd32c08fc5fcddfc69a168/modules/graphics/types/SpriteBatch.lua#L27) for each option. 

I can add it myself, but I'm pretty caught up with my studies at the moment... so if you want to give it another go I'd appreciate it :sweat_smile:

**Comment by davisdude** [comment]
Well for some reason the indents aren't displaying right (even though they look fine in the editor). I'm also not really sure if this is how you want it done.

**Comment by rm-code** [comment]
You just forgot a comma [here](https://github.com/rm-code/love-api/pull/16/files#diff-29b012f7c750ab85fa59f370f6b18045R195) :)

**Comment by davisdude** [comment]
Is that the right format?

**Comment by rm-code** [comment]
Looks good to me! Thanks a lot for your work :+1:

**Pull request merged**
