### PR TITLE
Allowed putting the directory inside a sub-folder.

### PR DESCRIPTION
**Pull request by davisdude**
I'm working on auto-generating the coloring for Vim. To do this, I have a batch file that looks something like this:
```batch
@echo off
:: If run via admin, cd is System32
cd %~dp0

:: Get most up-to-date version
rd love-api
git clone https://github.com/rm-code/love-api

"C:\Program Files\LOVE\0.10.0\love" . >out.txt

:: Cleanup
rd love-api
```

Then, main.lua looks like this:
```lua
api = require 'love-api.love_api'

-- etc.
-- Anything `print`ed will be output to out.txt
-- For instance: 
print( 'love.' .. api.functions[1].name )
```

Without these modifications, I get errors, because the files being required aren't in the base directory, so `require` cannot find the files.

### CODE REVIEW

**Comment by rm-code** [comment]
Thanks @davisdude :+1:

**Comment by davisdude** [comment]
You should note that if you require files with slashes instead of periods, this will not work correctly.
You can fix this with a `:gsub`

**Comment by rm-code** [comment]
@davisdude I almost forgot: Feel free to open a PR if you want your vim plugin added to the README.

**Comment by davisdude** [comment]
I will when I get home.

**Pull request merged**
